# Generated by Django 2.0.6 on 2018-07-26 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofilinfo',
            old_name='profil_pic',
            new_name='profile_pic',
        ),
    ]
